-- Lote 3: Cupido + Líder de Culto
--
-- ⚠️ NEUTERED: CREATE OR REPLACE FUNCTION removido para evitar overwrite pelo deploy.
-- Aplique via supabase db push (migrations 20260702203438..20260702203454).
--
-- Migration A (lot3_columns):
--   ALTER TABLE players ADD COLUMN soulmate_id UUID REFERENCES players(id) ON DELETE SET NULL;
--   ALTER TABLE players ADD COLUMN in_cult BOOLEAN NOT NULL DEFAULT false;
--   ALTER TABLE night_actions DROP CONSTRAINT night_actions_action_type_check;
--   ALTER TABLE night_actions ADD CONSTRAINT ... includes 'cult_convert';
--   ALTER TABLE players DROP CONSTRAINT players_role_check;
--   ALTER TABLE players ADD CONSTRAINT ... includes 'cupid', 'cult_leader';
--   ALTER TABLE rooms DROP CONSTRAINT rooms_status_check;
--   ALTER TABLE rooms ADD CONSTRAINT ... includes 'finished_soulmates_win', 'finished_cult_win';
--
-- Migration B (lot3_cupid_rpc):
--   submit_cupid_match(p_room_id, p_target_a, p_target_b) — cross-update soulmate_id
--
-- Migration C (lot3_soulmate_trigger):
--   FUNCTION after_player_death_soulmate() + TRIGGER trg_soulmate_death ON players
--   Se is_alive = false AND soulmate_id IS NOT NULL, mata o parceiro (coracao_partido)
--
-- Migration D (lot3_game_over):
--   check_game_over: PRIORIDADE 1 soulmates_win, PRIORIDADE 2 cult_win
--   trg_check_game_over: mesmas prioridades
--   host_end_game: +finished_soulmates_win, +finished_cult_win
--   execute_night_action: +cult_convert branch (UPDATE in_cult = true)
--   get_revealed_players: +in_cult, +soulmate_id columns
