-- Fix: resolve_night — ordem sequencial Padre → Lobos → Bruxa (veneno)
-- PASSO 1: Padre (is_blessed = TRUE)
-- PASSO 2: Lobisomens (verifica is_blessed + bodyguard)
-- PASSO 3: Bruxa veneno (verifica is_blessed do estado atual + bodyguard)
--
-- ⚠️ NEUTERED: CREATE OR REPLACE FUNCTION removido para evitar overwrite pelo deploy.
-- Aplique o SQL completo via Supabase SQL Editor manualmente.
-- O arquivo completo está em supabase/migrations/20260702182612_fix_priest_poison_order.sql
--
-- Resumo das mudanças no resolve_night:
-- 1. Lê ação priest_bless e seta is_blessed = TRUE (PASSO 1)
-- 2. Lê alvo dos lobos, verifica is_blessed + bodyguard (PASSO 2)
-- 3. Lê alvo do veneno, re-lê is_blessed (pós passos 1-2) + bodyguard (PASSO 3)
-- 4. Consome is_blessed ao salvar em cada passo
-- 5. last_event setado para lobisomem/veneno nos UPDATEs de morte
