-- Lot 3 fix: RPC get_cult_targets for CultLeaderPanel
--
-- ⚠️ NEUTERED: CREATE OR REPLACE FUNCTION removido para evitar overwrite pelo deploy.
-- Aplique via supabase db push (migration 20260702213720_cult_targets.sql).
--
-- Resumo:
--   CREATE OR REPLACE FUNCTION public.get_cult_targets(p_room_id UUID)
--   RETURNS JSONB
--   LANGUAGE plpgsql
--   SECURITY DEFINER
--   SET search_path = public
--   AS $$
--   SELECT jsonb_agg(...) FROM players p
--   WHERE p.room_id = p_room_id
--     AND p.is_alive = true
--     AND p.role NOT IN ('moderator', 'cult_leader')
--     AND (p.in_cult = false OR p.in_cult IS NULL)
--   $$
