-- Prince mechanic: survive lynching + reveal identity + advance to night
--
-- ⚠️ NEUTERED: CREATE OR REPLACE FUNCTION removido para evitar overwrite pelo deploy.
-- Aplique via supabase db push (migration 20260702213742_prince_mechanic.sql).
--
-- Resumo:
-- 1. resolve_day_vote: se v_target_role = 'prince', não mata, seta
--    current_phase = 'day', day_step = 'prince_reveal', last_event = { type: 'prince_reveal', victim_id, victim_name }
--
-- 2. advance_after_prince: avança de day_step = 'prince_reveal' para night,
--    turn_index + 1, night_step = 'sleeping'
